version: "3.3"

networks:
  hw6-network:

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password123
      - TZ=Europe/London
    volumes:
      - ./.db:/config
    #ports:
    #  - 5306:3306
    restart: unless-stopped
    networks:
      hw6-network:
        aliases:
          - mariadb

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseball
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
    restart: on-failure
    volumes:
      - ./src/:/src/
      - ./baseball.sql:/app/baseball.sql
      - ./src/hw5/:/src/hw5
      - ./src/hw5/output/:/src/hw5/output
    #ports:
    #  - 5307:3307
    networks:
      - hw6-network