version: "3.3"

services:
  mdb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mdb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - TZ=Europe/London
    volumes:
      - ./.db:/config
    restart: unless-stopped
    networks:
      - hw6-network

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    #image: baseball
    container_name: baseball
    depends_on:
      - mdb
    restart: unless-stopped
    volumes:
      - "./src/:/src/"
    networks:
      - hw6-network

networks:
  hw6-network:
